version: "3.7"
services:
  phaser-boilerplate:
    image: node:22-alpine3.19
    container_name: phaser-boilerplate
    ports:
      - 5173:5173
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: sh -c "npm install && npm run dev"
    restart: always